version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"